# Version information.
program_name:       "Songbird"
program_ver:        0.0.1
program_devs:       ["Michael Cvitanovich"]
program_web:        "galacticwingcommander"    
songbites_folder:   "./songbites/"
