# Version information.
program_name:       "Songbits"
program_ver:        0.0.1
program_devs:       ["Michael Cvitanovich"]
program_web:        "galacticwingcommander"    
songbits_folder:    "./fractals"
